spring:
  data:
    mongodb:
      uri: ${AUTH_SERVICE_MONGO_URI}
  profiles:
    active: "prod"

  security:
    oauth2:
      client:
        registration:
          discord:
            client-name: Discord
            client-id: ${DISCORD_APPLICATION_CLIENT_ID}
            client-secret: ${DISCORD_APPLICATION_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - identify
              - guilds
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
            user-info-authentication-method: header

server:
  error:
    whitelabel:
      enabled: false